### ISSUE TITLE
Issue when generating the dump using the "--r2rmlfile" pragma

### ISSUE THREAD

**Issue by edgardmarx** [tomatophantastico/sparqlmap#12]
The exception bellow is shown after running the dump action using the "--r2rmlfile" pragma.

_

> 16:57:35,485 [restartedMain] WARN   AbstractApplicationContext : Exception encou
> ntered during context initialization - cancelling refresh attempt: org.springfra
> mework.beans.factory.UnsatisfiedDependencyException: Error creating bean with na
> me 'sparqlMapCli': Unsatisfied dependency expressed through field 'sm'; nested e
> xception is org.springframework.beans.factory.BeanCreationException: Error creat
> ing bean with name 'configSparqlMap' defined in org.aksw.sparqlmap.common.Sparql
> MapSetup: Bean instantiation via factory method failed; nested exception is org.
> springframework.beans.BeanInstantiationException: Failed to instantiate [org.aks
> w.sparqlmap.core.SparqlMap]: Factory method 'configSparqlMap' threw exception; n
> ested exception is org.apache.jena.riot.RiotException: Failed to determine the c
> ontent type: (URI=mapping_test_2.rml : stream=null)
> 16:57:35,593 [restartedMain] ERROR  SpringApplication : Application startup fail
> ed
> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating
>  bean with name 'sparqlMapCli': Unsatisfied dependency expressed through field '
> sm'; nested exception is org.springframework.beans.factory.BeanCreationException
> : Error creating bean with name 'configSparqlMap' defined in org.aksw.sparqlmap.
> common.SparqlMapSetup: Bean instantiation via factory method failed; nested exce
> ption is org.springframework.beans.BeanInstantiationException: Failed to instant
> iate [org.aksw.sparqlmap.core.SparqlMap]: Factory method 'configSparqlMap' threw
>  exception; nested exception is org.apache.jena.riot.RiotException: Failed to de
> termine the content type: (URI=mapping_test_2.rml : stream=null)
>         at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanP
> ostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.j
> ava:588)
>         at org.springframework.beans.factory.annotation.InjectionMetadata.inject
> (InjectionMetadata.java:88)
>         at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanP
> ostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java
> :366)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBean
> Factory.populateBean(AbstractAutowireCapableBeanFactory.java:1225)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBean
> Factory.doCreateBean(AbstractAutowireCapableBeanFactory.java:552)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBean
> Factory.createBean(AbstractAutowireCapableBeanFactory.java:483)
>         at org.springframework.beans.factory.support.AbstractBeanFactory$1.getOb
> ject(AbstractBeanFactory.java:306)
>         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistr
> y.getSingleton(DefaultSingletonBeanRegistry.java:230)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBe
> an(AbstractBeanFactory.java:302)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean
> (AbstractBeanFactory.java:197)
>         at org.springframework.beans.factory.support.DefaultListableBeanFactory.
> preInstantiateSingletons(DefaultListableBeanFactory.java:759)
>         at org.springframework.context.support.AbstractApplicationContext.finish
> BeanFactoryInitialization(AbstractApplicationContext.java:866)
>         at org.springframework.context.support.AbstractApplicationContext.refres
> h(AbstractApplicationContext.java:542)
>         at org.springframework.boot.SpringApplication.refresh(SpringApplication.
> java:761)
>         at org.springframework.boot.SpringApplication.refreshContext(SpringAppli
> cation.java:371)
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java
> :315)
>         at org.aksw.sparqlmap.cli.SparqlMapStarter.main(SparqlMapStarter.java:25
> )
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.lang.reflect.Method.invoke(Unknown Source)
>         at org.springframework.boot.devtools.restart.RestartLauncher.run(Restart
> Launcher.java:49)
> Caused by: org.springframework.beans.factory.BeanCreationException: Error creati
> ng bean with name 'configSparqlMap' defined in org.aksw.sparqlmap.common.SparqlM
> apSetup: Bean instantiation via factory method failed; nested exception is org.s
> pringframework.beans.BeanInstantiationException: Failed to instantiate [org.aksw
> .sparqlmap.core.SparqlMap]: Factory method 'configSparqlMap' threw exception; ne
> sted exception is org.apache.jena.riot.RiotException: Failed to determine the co
> ntent type: (URI=mapping_test_2.rml : stream=null)
>         at org.springframework.beans.factory.support.ConstructorResolver.instant
> iateUsingFactoryMethod(ConstructorResolver.java:599)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBean
> Factory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:11
> 34)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBean
> Factory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1028)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBean
> Factory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBean
> Factory.createBean(AbstractAutowireCapableBeanFactory.java:483)
>         at org.springframework.beans.factory.support.AbstractBeanFactory$1.getOb
> ject(AbstractBeanFactory.java:306)
>         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistr
> y.getSingleton(DefaultSingletonBeanRegistry.java:230)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBe
> an(AbstractBeanFactory.java:302)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean
> (AbstractBeanFactory.java:202)
>         at org.springframework.beans.factory.config.DependencyDescriptor.resolve
> Candidate(DependencyDescriptor.java:207)
>         at org.springframework.beans.factory.support.DefaultListableBeanFactory.
> doResolveDependency(DefaultListableBeanFactory.java:1136)
>         at org.springframework.beans.factory.support.DefaultListableBeanFactory.
> resolveDependency(DefaultListableBeanFactory.java:1064)
>         at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanP
> ostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.j
> ava:585)
>         ... 21 more
> Caused by: org.springframework.beans.BeanInstantiationException: Failed to insta
> ntiate [org.aksw.sparqlmap.core.SparqlMap]: Factory method 'configSparqlMap' thr
> ew exception; nested exception is org.apache.jena.riot.RiotException: Failed to
> determine the content type: (URI=mapping_test_2.rml : stream=null)
>         at org.springframework.beans.factory.support.SimpleInstantiationStrategy
> .instantiate(SimpleInstantiationStrategy.java:189)
>         at org.springframework.beans.factory.support.ConstructorResolver.instant
> iateUsingFactoryMethod(ConstructorResolver.java:588)
>         ... 33 more
> Caused by: org.apache.jena.riot.RiotException: Failed to determine the content t
> ype: (URI=mapping_test_2.rml : stream=null)
>         at org.apache.jena.riot.RDFDataMgr.process(RDFDataMgr.java:854)
>         at org.apache.jena.riot.RDFDataMgr.parse(RDFDataMgr.java:667)
>         at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:212)
>         at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:105)
>         at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:96)
>         at org.apache.jena.riot.RDFDataMgr.loadModel(RDFDataMgr.java:325)
>         at org.aksw.sparqlmap.core.SparqlMapBuilder$SparqlMapMappingBuilder.mapp
> edBy(SparqlMapBuilder.java:110)
>         at org.aksw.sparqlmap.common.SparqlMapSetup.configSparqlMap(SparqlMapSet
> up.java:59)
>         at org.aksw.sparqlmap.common.SparqlMapSetup$$EnhancerBySpringCGLIB$$e0a5
> e8e1.CGLIB$configSparqlMap$0(<generated>)
>         at org.aksw.sparqlmap.common.SparqlMapSetup$$EnhancerBySpringCGLIB$$e0a5
> e8e1$$FastClassBySpringCGLIB$$565f69db.invoke(<generated>)
>         at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.j
> ava:228)
>         at org.springframework.context.annotation.ConfigurationClassEnhancer$Bea
> nMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
>         at org.aksw.sparqlmap.common.SparqlMapSetup$$EnhancerBySpringCGLIB$$e0a5
> e8e1.configSparqlMap(<generated>)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.lang.reflect.Method.invoke(Unknown Source)
>         at org.springframework.beans.factory.support.SimpleInstantiationStrategy
> .instantiate(SimpleInstantiationStrategy.java:162)
>         ... 34 more

_

**Comment by tomatophantastico** [comment]
Mapping files can be provided any serialization, however the suffix must follow the usual conventions.
In this case rename *.rml to *.ttl . Please note that rml != r2rml.
