### ISSUE TITLE
Issue using views

### ISSUE THREAD

**Issue by edgardmarx** [tomatophantastico/sparqlmap#14]
An error is being generated when using views:

19:43:18,961 [pool-3-thread-1] ERROR  MetaModelSelectiveDump : Error executing:
SELECT subquery."parent", subquery."id" FROM (select id, parent from (select id,
 parent from (Select id, Mid(vater, 4, len(vater)) as parent from BioTabelle1) U
NION (Select id, Mid(mutter,4,len(mutter)) as parent from BioTabelle1)) where pa
rent is not null) subquery

It seems that the query is been executed with quotation marks.
I tried to execute the query in the DB console with the quotation, and it also generates an error:

**SELECT subquery."parent", subquery."id" ...**

The query without quotation executed successfully:

**SELECT subquery.parent, subquery.id**

**Comment by tomatophantastico** [comment]
There might be some internal conversion of the query in the underlying database going on, can you try to quote the projected columns in your subquery/view?

**Comment by edgardmarx** [comment]
I've tried to rewrite the query in many forms in SQL console like:

> Select t."id", t."parent" from (select "id", "parent" from (Select "id", Mid(vater, 4, len(vater)) as "parent" from BioTabelle1) UNION (Select "id", Mid(mutter,4,len(mutter)) as "parent" from BioTabelle1)) as t where t."parent" is not null;

or

> Select t."id", t."parent" from (select id, parent from (Select id, Mid(vater, 4, len(vater)) as parent from BioTabelle1) UNION (Select id, Mid(mutter,4,len(mutter)) as parent from BioTabelle1)) as t where t."parent" is not null;

and it does not work, the main problem is that seems the MS ACCESS query interpreter does not recognize t."parent", it throws an error:"Invalid Use of ".", "!", or "()" ..."

**Comment by tomatophantastico** [comment]
SparqlMap uses (inderectly) Jackcess to map MS Access.

I will give it a shot and check, what kind of queries can be execute there, but no guarantee. 
Please bear in mind, that most non-MS ways of accessing an Access DB will lack some features.

Or are you connecting to MS ACCESS via jdbc/odbc?

**Comment by edgardmarx** [comment]
I am using Access SQL console.

Notice that I've tried SPARQLMAP with the following SQL:
> select id, parent from (Select id, vater as parent from BioTabelle1);

and

> select id, parent from (Select id, vater as parent from BioTabelle1) as table

and

> select t."id", t."parent" from (Select id, vater as parent from BioTabelle1) as t;

and

> select t.id, t.parent from (Select id, vater as parent from BioTabelle1) as t;

, but it didn't work.

However, it works with the following:

> Select id, vater as parent from BioTabelle1

So, it seems that the SPARQLMap has a problem to parse nested SQL.

**Comment by tomatophantastico** [comment]
Please report full stacktrace.

**Comment by edgardmarx** [comment]
> D:\emarx\phd\pfarrabuch\sparqlmap-client-0.7.4>java -classpath lib\* org.aksw.sp
> arqlmap.cli.SparqlMapStarter --action=dump --r2rmlfile="mapping_test_2.ttl" --ds
> .type=ACCESS --ds.url="KPS-BIO-A-G 2010  akt.mdb" > dump2.ttl
> 15:41:24,644 [restartedMain] WARN   AccessDataContext : Failed to get PK index i
> nfo for table: Table@4c94fb68[
>   type: 78 (USER)
>   name: Konvertierungsfehler
>   rowCount: 1
>   columnCount: 3
>   indexCount(data): 0
>   logicalIndexCount: 0
>   columns: [
>     Column@4abc0192[
>       name: (Konvertierungsfehler) Objekttyp
>       type: 0xa (TEXT)
>       number: 0
>       length: 510
>       variableLength: true
>       compressedUnicode: false
>       textSortOrder: SortOrder[1033(0)]
>     ],
>     Column@e474a01[
>       name: (Konvertierungsfehler) Objektname
>       type: 0xa (TEXT)
>       number: 1
>       length: 510
>       variableLength: true
>       compressedUnicode: false
>       textSortOrder: SortOrder[1033(0)]
>     ],
>     Column@2c5bc9be[
>       name: (Konvertierungsfehler) Fehlerbeschreibung
>       type: 0xc (MEMO)
>       number: 2
>       length: 0
>       variableLength: true
>       compressedUnicode: false
>       textSortOrder: SortOrder[1033(0)]
>     ]
>   ]
>   indexes: [
>   ]
>   ownedPages: InlineHandler[range=(952-1464),pageNumbers=[954]]
> ]
> java.lang.IllegalArgumentException: Table Konvertierungsfehler does not have a p
> rimary key index
>         at com.healthmarketscience.jackcess.impl.TableImpl.getPrimaryKeyIndex(Ta
> bleImpl.java:481)
>         at com.healthmarketscience.jackcess.impl.TableImpl.getPrimaryKeyIndex(Ta
> bleImpl.java:72)
>         at org.eobjects.metamodel.access.AccessDataContext.getMainSchema(AccessD
> ataContext.java:107)
>         at org.apache.metamodel.QueryPostprocessDataContext.getSchemaByNameInter
> nal(QueryPostprocessDataContext.java:480)
>         at org.apache.metamodel.AbstractDataContext.getSchemaByName(AbstractData
> Context.java:206)
>         at org.apache.metamodel.AbstractDataContext.getDefaultSchema(AbstractDat
> aContext.java:125)
>         at org.apache.metamodel.AbstractDataContext.getSchemaByToken(AbstractDat
> aContext.java:510)
>         at org.apache.metamodel.AbstractDataContext.getTableByQualifiedLabel(Abs
> tractDataContext.java:396)
>         at org.apache.metamodel.query.parser.FromItemParser.parseTableItem(FromI
> temParser.java:135)
>         at org.apache.metamodel.query.parser.FromItemParser.parse(FromItemParser
> .java:88)
>         at org.apache.metamodel.query.parser.QueryPartParser.parseItem(QueryPart
> Parser.java:122)
>         at org.apache.metamodel.query.parser.QueryPartParser.parse(QueryPartPars
> er.java:70)
>         at org.apache.metamodel.query.parser.QueryPartParser.parse(QueryPartPars
> er.java:86)
>         at org.apache.metamodel.query.parser.QueryParser.parseFromClause(QueryPa
> rser.java:155)
>         at org.apache.metamodel.query.parser.QueryParser.parse(QueryParser.java:
> 86)
>         at org.aksw.sparqlmap.core.SparqlMap.validateMapping(SparqlMap.java:486)
> 
>         at org.aksw.sparqlmap.core.SparqlMapBuilder$SparqlMapMappingBuilder.crea
> te(SparqlMapBuilder.java:139)
>         at org.aksw.sparqlmap.common.SparqlMapSetup.configSparqlMap(SparqlMapSet
> up.java:61)
>         at org.aksw.sparqlmap.common.SparqlMapSetup$$EnhancerBySpringCGLIB$$9a70
> 36dc.CGLIB$configSparqlMap$0(<generated>)
>         at org.aksw.sparqlmap.common.SparqlMapSetup$$EnhancerBySpringCGLIB$$9a70
> 36dc$$FastClassBySpringCGLIB$$53b44960.invoke(<generated>)
>         at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.j
> ava:228)
>         at org.springframework.context.annotation.ConfigurationClassEnhancer$Bea
> nMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
>         at org.aksw.sparqlmap.common.SparqlMapSetup$$EnhancerBySpringCGLIB$$9a70
> 36dc.configSparqlMap(<generated>)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.lang.reflect.Method.invoke(Unknown Source)
>         at org.springframework.beans.factory.support.SimpleInstantiationStrategy
> .instantiate(SimpleInstantiationStrategy.java:162)
>         at org.springframework.beans.factory.support.ConstructorResolver.instant
> iateUsingFactoryMethod(ConstructorResolver.java:588)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBean
> Factory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:11
> 34)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBean
> Factory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1028)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBean
> Factory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBean
> Factory.createBean(AbstractAutowireCapableBeanFactory.java:483)
>         at org.springframework.beans.factory.support.AbstractBeanFactory$1.getOb
> ject(AbstractBeanFactory.java:306)
>         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistr
> y.getSingleton(DefaultSingletonBeanRegistry.java:230)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBe
> an(AbstractBeanFactory.java:302)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean
> (AbstractBeanFactory.java:202)
>         at org.springframework.beans.factory.config.DependencyDescriptor.resolve
> Candidate(DependencyDescriptor.java:207)
>         at org.springframework.beans.factory.support.DefaultListableBeanFactory.
> doResolveDependency(DefaultListableBeanFactory.java:1136)
>         at org.springframework.beans.factory.support.DefaultListableBeanFactory.
> resolveDependency(DefaultListableBeanFactory.java:1064)
>         at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanP
> ostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.j
> ava:585)
>         at org.springframework.beans.factory.annotation.InjectionMetadata.inject
> (InjectionMetadata.java:88)
>         at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanP
> ostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java
> :366)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBean
> Factory.populateBean(AbstractAutowireCapableBeanFactory.java:1225)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBean
> Factory.doCreateBean(AbstractAutowireCapableBeanFactory.java:552)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBean
> Factory.createBean(AbstractAutowireCapableBeanFactory.java:483)
>         at org.springframework.beans.factory.support.AbstractBeanFactory$1.getOb
> ject(AbstractBeanFactory.java:306)
>         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistr
> y.getSingleton(DefaultSingletonBeanRegistry.java:230)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBe
> an(AbstractBeanFactory.java:302)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean
> (AbstractBeanFactory.java:197)
>         at org.springframework.beans.factory.support.DefaultListableBeanFactory.
> preInstantiateSingletons(DefaultListableBeanFactory.java:759)
>         at org.springframework.context.support.AbstractApplicationContext.finish
> BeanFactoryInitialization(AbstractApplicationContext.java:866)
>         at org.springframework.context.support.AbstractApplicationContext.refres
> h(AbstractApplicationContext.java:542)
>         at org.springframework.boot.SpringApplication.refresh(SpringApplication.
> java:761)
>         at org.springframework.boot.SpringApplication.refreshContext(SpringAppli
> cation.java:371)
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java
> :315)
>         at org.aksw.sparqlmap.cli.SparqlMapStarter.main(SparqlMapStarter.java:25
> )
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.lang.reflect.Method.invoke(Unknown Source)
>         at org.springframework.boot.devtools.restart.RestartLauncher.run(Restart
> Launcher.java:49)
> 15:41:24,684 [restartedMain] WARN   SparqlMapBuilder$SparqlMapMappingBuilder : C
> annot parse view query of triplesmap: file:///D:/emarx/phd/pfarrabuch/sparqlmap-
> client-0.7.4/mapping_test_2.ttl#VaterMutterTriplesMap
> Cannot bind col "parent" in mapping file:///D:/emarx/phd/pfarrabuch/sparqlmap-cl
> ient-0.7.4/mapping_test_2.ttl#VaterMutterTriplesMap
> Cannot bind col "parent" in mapping file:///D:/emarx/phd/pfarrabuch/sparqlmap-cl
> ient-0.7.4/mapping_test_2.ttl#VaterMutterTriplesMap
> Cannot parse view query of triplesmap: file:///D:/emarx/phd/pfarrabuch/sparqlmap
> -client-0.7.4/mapping_test_2.ttl#VaterMutterTriplesMap
> Cannot bind col "parent" in mapping file:///D:/emarx/phd/pfarrabuch/sparqlmap-cl
> ient-0.7.4/mapping_test_2.ttl#VaterMutterTriplesMap
> Cannot bind col "id" in mapping file:///D:/emarx/phd/pfarrabuch/sparqlmap-client
> -0.7.4/mapping_test_2.ttl#VaterMutterTriplesMap
> Cannot parse view query of triplesmap: file:///D:/emarx/phd/pfarrabuch/sparqlmap
> -client-0.7.4/mapping_test_2.ttl#VaterMutterTriplesMap
> Cannot bind col "parent" in mapping file:///D:/emarx/phd/pfarrabuch/sparqlmap-cl
> ient-0.7.4/mapping_test_2.ttl#VaterMutterTriplesMap
> 15:41:28,321 [pool-3-thread-1] ERROR  MetaModelSelectiveDump : Error executing:
> SELECT subquery."parent", subquery."id" FROM (select * from (Select id, vater as
>  parent from BioTabelle1)) subquery
> java.lang.IllegalArgumentException: FromItem type not supported: (select * from
> (Select id, vater as parent from BioTabelle1)) subquery
>         at org.apache.metamodel.QueryPostprocessDataContext.materializeFromItem(
> QueryPostprocessDataContext.java:358)
>         at org.apache.metamodel.QueryPostprocessDataContext.executeQuery(QueryPo
> stprocessDataContext.java:192)
>         at org.aksw.sparqlmap.backend.metamodel.translate.MetaModelSelectiveDump
> .dump(MetaModelSelectiveDump.java:168)
>         at org.aksw.sparqlmap.backend.metamodel.translate.MetaModelSelectiveDump
> .run(MetaModelSelectiveDump.java:334)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
>         at java.lang.Thread.run(Unknown Source)
> 
> >

**Comment by tomatophantastico** [comment]
Put simple, the backend does not allow SQL queries, so you cannot use views here.
This a limitation on the Access mapper.

If you really need it, try a JDBC/ODBC bridge.
