### ISSUE TITLE
Error executing SPARQLMap via command line

### ISSUE THREAD

**Issue by edgardmarx** [tomatophantastico/sparqlmap#15]
I am getting the above error when trying to execute SPARQLMap 0.7.5 Snapshot.
Seems that the required parameters are there but I am still receiving the error message.

Command: 

> java -classpath lib\* or
> g.aksw.sparqlmap.cli.SparqlMapStarter --action=dump --r2rmlfile="mapping_test_2. ttl" --
> ds.type=ACCESS --ds.url="KPS-BIO-A-G 2010 akt.mdb"

Errors: 

> Error processing command line options: The following options are required: -url,
>  --ds.url -a, --action

**Comment by tomatophantastico** [comment]
fixed
