### ISSUE TITLE
Conditional Mappings for SubjectMaps

### ISSUE THREAD

**Issue by edgardmarx** [tomatophantastico/sparqlmap#20]
It will be highly appreciated if we have a conditional mapping for r2rml:subjectMap.
In case there is, it might have some bug in SPARQLMap 0.7.5 SNAPSHOT 2.

The problem is that although I can avoid the generation of undesirable object, there is not too much to do to avoid generating the subjects.

**Comment by tomatophantastico** [comment]
actually, this should already work, can you link to the mapping?

**Comment by edgardmarx** [comment]
The mapping bellow is suppose to map only when the string do not start with '.' or '°' characters.
If I add the conditional mapping to subject, the triples are not generated (i.e. even subjects that do not start with the mentioned characters are not generated).
However, when I remove it, the tool works as expected.

> <#Places3TableView> r2rml:sqlQuery """
> select distinct Berufung1_Ort from BioTabelle1;
> """.
> <#Places3TriplesMap>
>     r2rml:logicalTable <#Places3TableView>;
>     r2rml:subjectMap [
>         r2rml:template "http://pfarrerbuch.aksw.org/kps/ort/{\"Berufung1_Ort\"}";		
>         r2rml:class hp:Place;
> 		smap:requiredPattern """^[^°|^.].\*$"""
>     ];
>     r2rml:predicateObjectMap [
>         r2rml:predicate hp:nameOfPlace;
>         r2rml:objectMap [
> 			r2rml:column "\"Berufung1_Ort\"";
> 			r2rml:datatype r2rml:Literal;
> 			smap:requiredPattern """^[^°|^.].\*$"""
> 		];
>     ];
> 	r2rml:predicateObjectMap [
>         r2rml:predicate rdfs:label;
>         r2rml:objectMap [
> 			r2rml:column "\"Berufung1_Ort\"";
> 			r2rml:datatype r2rml:Literal;
> 			smap:requiredPattern """^[^°|^.].\*$"""
> 		];
>     ].

**Comment by edgardmarx** [comment]
it seems there is another problem, the problem exist only when I run more than one triple mapping, in the case above, it seems to be working.
I will invalidate and return to you when it gets clear.
